services:
  albums:
    build: ./server
    ports:
      - "8080:8080"

  master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/mnt/locust
    command: -f /mnt/locust/${LOCUSTFILE:-locustfile.py} --master -H http://albums:8080

  worker:
    image: locustio/locust
    volumes:
      - ./locust:/mnt/locust
    command: -f /mnt/locust/${LOCUSTFILE:-locustfile.py} --worker --master-host master
    depends_on:
      - master
